[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "read-temperature"
version = "0.1.0"
edition = "2018"

[dependencies]
co2mon = "2.0"
reqwest = "0.11"
time = "0.3"
tokio = { version = "1.11", features = ["io-util", "rt", "sync", "time"] }
tokio-serial = "5.4"
