[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "read-temperature"
version = "0.1.0"

[dependencies]
bytes = "0.4"
failure = "0.1.1"
futures = "0.1"
hyper = { git = "https://github.com/hyperium/hyper" }
tokio-io = "0.1"
tokio-serial = { git = "https://github.com/berkowski/tokio-serial" }
tokio-service = "0.1"
tokio-timer = "0.2"
tokio = "0.1.5"
http = "0.1.5"
