[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "read-temperature"
version = "0.1.0"

[dependencies]
bytes = "0.4"
futures = "0.1"
http = "0.1"
hyper = "0.12"
tokio-codec = "0.1"
tokio-serial = "3.2"
tokio-timer = "0.2"
tokio = "0.1"
