[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "read-temperature-tokio"
version = "0.1.0"

[dependencies]
bytes = "0.4"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-serial = "0.6"
tokio-service = "0.1"
tokio-timer = "0.1"
